### ISSUE TITLE
Metrics: User activity feed

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-theme#1019] opened 2020-07-14 17:53 UTC
As a user, I would like a way to see what I have done. Potentially this data could be accessed via the User Profile page (accessed via the user name on the blue nav strip) by having a tile listing history.

**Comment by corsacca** [comment] 2020-07-17 08:31
Please expand on what you would expect to see in this user history.

**Comment by mikeallbutt** [comment] 2020-07-17 17:29
> Please expand on what you would expect to see in this user history.

Maybe the notifications page could be expanded to include that type of information. 
The history that I would find helpful would be things like:

- a list of updates by date of a contact and group that can then be expanded to see what was done. Doesn't need to be the whole report, but a way to get to the contact or group to add or edit more info.

- {contact/group} updated by {User};
-- {User} adjusted details for {contact/group};
-- {User} adjusted details for {contact/group};
-- {User} wrote a comment about {contact/group}; 
-- {User} adjusted member list {group};
-- {User} adjusted group health for {group};
-- {User} adjusted tag for {contact/group};

-

**Comment by corsacca** [comment] 2021-04-16 14:44
@mikeallbutt is this a duplicate of https://github.com/DiscipleTools/disciple-tools-theme/issues/711 ?

**Comment by corsacca** [comment] 2021-04-19 11:21
Great. Thanks @mikeallbutt! We'll combine the issues into #711.

**Comment by corsacca** [comment] 2021-06-04 12:44
Upon further thought the 2 issues are not quite the same. This one is more of an activity feed, then other is more a curated highlights list.

**Comment by corsacca** [comment] 2021-06-04 12:48
Let's build this in the metrics section, under personal. 
Code can be copied from the user management activity tile. Thought we want to remove the "logged in" messages

**Comment by squigglybob** [comment] 2021-09-10 14:11
> > Please expand on what you would expect to see in this user history.
> 
> Maybe the notifications page could be expanded to include that type of information.
> The history that I would find helpful would be things like:
> 
> * a list of updates by date of a contact and group that can then be expanded to see what was done. Doesn't need to be the whole report, but a way to get to the contact or group to add or edit more info.
> * {contact/group} updated by {User};
>   -- {User} adjusted details for {contact/group};
>   -- {User} adjusted details for {contact/group};
>   -- {User} wrote a comment about {contact/group};
>   -- {User} adjusted member list {group};
>   -- {User} adjusted group health for {group};
>   -- {User} adjusted tag for {contact/group};
> * This could be kept simple by logging changes per tile/area for a contact or group.

Just so I can understand fully before jumping on this issue. Is this for a user looking at their own personal changes that they have made?

**Comment by corsacca** [comment] 2021-09-10 14:59
Correct

**Closed** 2021-09-21 14:45 UTC
Labels: help wanted
