### ISSUE TITLE
WP admin: Limit languages available 

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-theme#953] opened 2020-04-22 14:45 UTC
If we are going to have a growing list of translations, it would be good to have a WP admin tab that lists the languages available and allows the admin to turn off ones (using a tick-a-box option) that they don’t want to offer.

eg. I won’t need Arabic and others won’t need spanish. Most instances will only use a few and not the whole list, so reducing the list would help in the overhead (maybe?) but also less of a long list per field item that needs to be translated.

**Comment by corsacca** [comment] 2021-04-13 17:17
Is this issue a duplicate of https://github.com/DiscipleTools/disciple-tools-theme/issues/1016?

**Comment by mikeallbutt** [comment] 2021-04-16 12:59
Yes it seems to be that same and the other issue is explained better.

But if either of these aren't implemented, then setting up dt as a multi lingual instance is more difficult than if this was implemented.

**Comment by corsacca** [comment] 2021-04-16 14:53
Thank you Mike.
This issue is a duplicate and better explained by https://github.com/DiscipleTools/disciple-tools-theme/issues/1016

**Closed by corsacca** 2021-04-16 14:53 UTC
Labels: translation
