### ISSUE TITLE
HTML character encoding in Contact Title/Name

### ISSUE THREAD

**Issue by zdmc23** [DiscipleTools/disciple-tools-theme#994] opened 2020-06-12 02:29 UTC
I stumbled upon this while opening up a similar issue for the Mobile App.  It looks like the comments handle HTML special chars properly, but the Contact Title/Name is displaying it in encoded format

Ref: https://github.com/DiscipleTools/disciple-tools-theme/issues/815

![Screenshot from 2020-06-11 22-18-09](https://user-images.githubusercontent.com/191707/84458358-d9c30380-ac32-11ea-82ff-01aabef4b7cc.png)

**Comment by corsacca** [comment] 2020-06-12 09:41
Linked to https://github.com/DiscipleTools/disciple-tools-theme/issues/929

**Comment by micahmills** [comment] 2020-07-03 08:34
<img width="820" alt="Screen Shot 2020-07-03 at 11 25 38 AM" src="https://user-images.githubusercontent.com/2531805/86448974-2d031000-bd20-11ea-9134-38fbf3c9a0ce.png">

I am not seeing this on my local copy of the repo, but I do see it in my disciple.tools demo instance. Is there a difference in what is running there versus what is coming from the master branch?

**Comment by corsacca** [comment] 2020-07-03 09:28
Users with Macs seem to trigger the issue, then it is displayed for all. I haven't been able to reproduce it locally either.

**Comment by corsacca** [comment] 2020-07-30 15:47
Duplicate of #929

**Closed by corsacca** 2020-07-30 15:47 UTC
Labels: bug
