### ISSUE TITLE
Language change doesn't reflect changes

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-theme#879] opened 2019-12-14 11:57 UTC
My instance of DT uses `language1` as the default language but in the `my.discipletools.in/settings/` when I go to edit the language, and set it to `language2` for a user, the change isn't recognised if on the user profile page in /wp-admin/profile.php is set to use `site default`.

**Comment by mikeallbutt** [comment] 2019-12-14 12:03
After doing some investigating, I think the issue is that what the first item says in the dropdown list on the /settings/ page of `English (United States)` is actually referring to `Site Default` which is not what it says. 

![Screenshot 2019-12-14 05 59 32](https://user-images.githubusercontent.com/43966676/70848432-fa9ecd80-1e36-11ea-8fd5-1e7e82a57e43.png)

**Comment by corsacca** [comment] 2019-12-14 13:02
This looks like a duplicate of: https://github.com/DiscipleTools/disciple-tools-theme/issues/697

**Comment by mikeallbutt** [comment] 2019-12-14 13:35
> This looks like a duplicate of: #697

It is significantly different.

**Comment by corsacca** [comment] 2020-02-21 16:06
@mikeallbutt, I think @micahmills just fixed this issue. Would you be able to confirm it on your end?

**Comment by micahmills** [comment] 2020-02-21 16:34
This needs further testing. I am not seeing it when I test with a user that is assigned a DT role, but on my main wordpress Administrator user I might still be seeing it.

**Comment by micahmills** [comment] 2020-03-09 07:58
Ok So I have more information to add here and @mikeallbutt if you are able to confirm this on your installation it would be helpful. So it appears that something int DT is causing a bug that an Admin users language settings are overriding the Site Default languages. For instance, If I set the Site Default language (Settings->General->Site Language) to Spanish, but then change my admin users language to English in the user profile either in WP-admin or in DT it will change the site default language to English and I will be unable to change it in (Settings->General->Site Language). 

If I have non-admin user they are able to change their language to user the site default or some other settings without any problem. 

The implications of this are that you can't set the site default to one language and have the admin use English without every user manually changing their language settings to their local language. It also means that all emails for new users will go out in the Admin's language instead of the site default.

I am looking to see if I can find what causes this.

**Comment by micahmills** [comment] 2020-03-09 07:59
I did confirm that it is something in DT because I deactivated the DT theme and I was able to set the site default language independently of the Admin's user language.

**Closed** 2020-03-10 09:09 UTC
Labels: translation
