### ISSUE TITLE
Make tiles collapsable

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-theme#850] opened 2019-12-03 14:42 UTC
Some tiles use up a lot of space and aren't needed often, so it would be useful to have the ability of collapse the tiles, so that only the heading of the tile is shown. This feature is currently available in the custom tiles.

![Screenshot 2019-12-03 08 37 31](https://user-images.githubusercontent.com/43966676/70060689-a1b67600-15a8-11ea-8978-06b4e7fa19f8.png)

![Screenshot 2019-12-03 08 41 40](https://user-images.githubusercontent.com/43966676/70060759-beeb4480-15a8-11ea-8939-326135130dd1.png)

(Assign me to this if you like and I will implement it.)

**Comment by corsacca** [comment] 2019-12-03 14:45
Is this a duplicate of https://github.com/DiscipleTools/disciple-tools-theme/issues/749 ?

**Comment by mikeallbutt** [comment] 2019-12-03 14:51
> Is this a duplicate of #749 ?

Oops - yes it is the same issue as #749 .

**Closed** 2019-12-03 14:52 UTC
